title: IxVentures
description: >-
  IxVentures site powered by Jekyll + Minima.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Add collections
collections:
  projects:
    output: true
