title: IxVentures Studio
description: A portfolio of projects from IxVentures
url: "https://ixventures.studio"
baseurl: ""   # leave empty unless the site is served in a subpath

collections:
  projects:
    output: true
    permalink: /projects/:name/
