title: IxVenture
description: Building something amazing with AI

# Use empty baseurl by default, but allow GitHub Pages to override
baseurl: "" 
url: "" 

theme: minima

# Site version
version: 0.1.5

collections:
  projects:
    output: true
    permalink: /projects/:path/
