title: IxVenture
description: Building something amazing with AI

# Use empty baseurl by default, but allow GitHub Pages to override
baseurl: "" 
url: "" 

theme: minima

# Custom settings
version: 0.1.2

# Enable project pages
collections:
  projects:
    output: true
    permalink: /projects/:name/
